--- 
- name: Get system interfaces
  ansible.builtin.uri:
    url: "{{pfserver_webadmin_url}}/api/v1/configurator/config/interfaces"
    method: GET
    status_code: 200
    validate_certs: False
    return_content: yes
    body_format: json
  register: get_system_int
  until: get_system_int.status == 200
  ignore_errors: yes
  retries: 5
  delay: 10

- name: Get system dns servers
  ansible.builtin.uri:
    url: "{{pfserver_webadmin_url}}/api/v1/configurator/config/system/dns_servers"
    method: GET
    status_code: 200
    validate_certs: False
    return_content: yes
    body_format: json
  register: get_system_dns_servers
  until: get_system_dns_servers.status == 200
  ignore_errors: yes
  retries: 5
  delay: 10

- name: configure_mgmt_int
  ansible.builtin.uri:
    url: "{{pfserver_webadmin_url}}/api/v1/configurator/config/interface/{{id[0]}}"
    method: PATCH
    status_code: 200
    body_format: json
    validate_certs: False
    body: >-
      {
        "ipaddress": "{{ipaddress[0]}}",
        "netmask": "{{netmask[0]}}",
        "type": "management",
        "additional_listening_daemons": ["portal"]
      }
  register: result
  until: result.status == 200
  retries: 5
  delay: 10
  vars:
    id: "{{ get_system_int | to_json | from_json | community.general.json_query('json.items[*].id') }}"
    ipaddress: "{{ get_system_int | to_json | from_json | community.general.json_query('json.items[*].ipaddress') }}"
    netmask: "{{ get_system_int | to_json | from_json | community.general.json_query('json.items[*].netmask') }}"

- name: configure dns servers
  ansible.builtin.uri:
    url: "{{pfserver_webadmin_url}}/api/v1/configurator/config/system/dns_servers"
    method: PUT
    status_code: 200
    body_format: json
    validate_certs: False
    headers:
      "Content-Type": "application/json"
    body: >-
      {
        "dns_servers": ["{{ get_system_dns_servers.json.dns_servers[0] }}", "{{ get_system_dns_servers.json.dns_servers[1] }}"]
      }
  register: result
  until: result.status == 200
  retries: 5
  delay: 2
  ignore_errors: True


