
- name: Check configurator disabled
  ansible.builtin.uri:
    url: "{{pfserver_webadmin_url}}/api/v1/configurator/config/base/advanced"
    method: PATCH
    status_code: 200
    validate_certs: False
    body_format: json
    headers:
      "Content-Type": "application/json"
    body: >-
      {
        "configurator": "disabled"
      }
  register: result
  until: result.status == 200 and "Settings updated" in result.json.message 
  ignore_errors: true
  retries: 5
  delay: 10
