name: packetfence_deb_package
on:
  push:
    branches: [ "features/inv-73" ]
#    paths:
#      - 'addons/packetfence-perl/**'
      
jobs:
  build_image:
#  build:

    runs-on: test-igor
    # services:
    #   registry:
    #     image: registry:2
    #     ports:
    #       - 5000:5000
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ vars.USER_GITHUB }}
#          password: ${{ secrets.TOKEN_GITHUB }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: packetfence-perl-debian

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: './addons/packetfence-perl'
          push: false
          load: true
          tags: |
            packetfence/packetfence-perl-debian:v1.21
            packetfence/packetfence-perl-debian:latest
            localhost:5000/packetfence/packetfence-perl-debian:latest
            localhost:5000/packetfence/packetfence-perl-debian:v1.21
          file: ./addons/packetfence-perl/Dockerfile-debian
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/packetfence/packetfence-perl-debian:latest
      
      - name: bash-version-ls-la-first
        run: |
          echo "::add-mask::asdfsadf"
          ls -ltr /
          pwd
          ls -ltr ./
          env
          docker image ls

      - name: build debian package
        uses: addnab/docker-run-action@v3
        with:
#            image: localhost:5000/packetfence/packetfence-perl-debian:latest
            image: packetfence/packetfence-perl-debian:latest
            options: --rm -v ${{ github.workspace }}/addons/packetfence-perl/:/root -v /mnt/:/mnt/output
            shell: /bin/bash
            run: |
                set -e && python3 install_cpan.py -d dependencies.csv -vi true && 
                ./make_tar_from_source.sh

      - name: check if the package is created
        run: |
          ls -la /mnt/debian/packages/

#   build_debian_package:
#     # services:
#     #   registry:
#     #     image: registry:2
#     #     ports:
#     #       - 5000:5000
#     needs: build_image
#     runs-on: test-igor
#     container:
#       image: localhost:5000/packetfence/packetfence-perl-debian:latest
#       env:
#         NODE_ENV: development
# #      volumes:
# #        - /tmp/:/mnt/output

#     steps:
#       - name: Check for dockerenv file
#         run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
#       - name: sadfasdfsd 
#         run: |
#           pwd
#           ls -ltr ./
#           ls -ltr /root
#           ls -ltr /usr/local/pf/lib/perl_modules/lib/perl5/
#           env
#           python3 install_cpan.py -d dependencies.csv -vi true 
#           ./make_tar_from_source.sh
          


  unit-test:
    needs: ['build_image']
    runs-on: test-igor
    container:
      image: ubuntu:20.04
#      env:
#        NODE_ENV: development
      volumes:
        - /mnt/debian/packages/:/mnt
#      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
      - name: install the package
        run: |
          cat /etc/*release
          env
          ls -la /mnt
          dpkg -i /mnt/*.deb

  sign_package:
    needs: ['build_image', 'unit-test']
    runs-on: test-igor
    container:
      image: debian:11.0
#      env:
#        NODE_ENV: development
      volumes:
        - /mnt/debian/packages/:/mnt
#      options: --cpus 1
    steps:
      - name: Install debian dependenecies
        run:  apt update && apt install gpg dpkg-sig -y

      - name: import private key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --pinentry-mode loopback --import

      - name: Sign the package
        run: dpkg-sig -k  B022C48D3D6373D7FC256A8CCB2D3A2AA0030E2C  --sign builder /mnt/*.deb

      - name: Verifiy the signarure of package
        run: gpg --verify  /mnt/*.deb


  push_docker-image_and_deb-package: 
    needs: ['build_image', 'unit-test', 'sign_package']
    runs-on: test-igor

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: './addons/packetfence-perl'
        push: true
        tags: |
          localhost:5000/packetfence/packetfence-perl-debian:latest
          localhost:5000/packetfence/packetfence-perl-debian:v1.21
        file: ./addons/packetfence-perl/Dockerfile-debian
        cache-from: type=gha
#        cache-to: type=gha,mode=max
