name: Packetfence-perl image/package build 
on:
  workflow_call:
    inputs:
      _IMAGE_TYPE:
        required: True
        type: string
      _WORKDIR:
        required: True
        type: string

jobs:
  build_package:
    runs-on: packetfence-perl-package-build
    container:
      image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/${{ inputs._IMAGE_TYPE == 'rhel8' && 'centos:8' || 'debian:11.0'}}
      volumes:
        - ${{ github.workspace }}/:${{ inputs._WORKDIR }}
    steps:     

      - name: Install RHEL dependencies ${{ inputs._IMAGE_TYPE }}
        run: dnf -y install rpm-sign python39 && python3.9 -m pip install -q  -U pip && pip install -q pynacl requests

      - name: Build package ${{inputs._IMAGE_TYPE}}
        shell: sh
        run: |
          set -e && export FINGERBANK_API_KEY=$(set -e && python3  ${{ inputs._WORKDIR }}/addons/packetfence-perl/psono.py --api_key_id=${{ secrets.PSONO_API_KEY_ID }} --api_key_secret_key=${{ secrets.PSONO_API_KEY_SECRET_KEY }} --secret_id=${{ vars.PSONO_BUILDS_KEY_FINGERBANK }} --return_value=password)
          cd ${{ inputs._WORKDIR }}/addons/perl-client/
          set -e &&  make SHELL='sh' -e ${{ inputs._IMAGE_TYPE == 'rhel8' && 'build_rpm' || 'debian:11.0'}}
          ls -la ${{ inputs._WORKDIR }}/packetfence/addons/perl-client/result/${{ inputs._IMAGE_TYPE == 'rhel8' && 'centos/8' || 'debian/bullseye'}}
    
      - name: Upload the package to artifactory ${{inputs._IMAGE_TYPE}}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACTORY_NAME }}
          path:  ${{ inputs._WORKDIR }}/packetfence/addons/perl-client/result/${{ inputs._IMAGE_TYPE == 'rhel8' && 'centos/8' || 'debian/bullseye'}}/${{ env.PACKAGE_NAME }}
        env:
          PACKAGE_NAME: ${{ inputs._IMAGE_TYPE == 'rhel8' &&  'fingerbank-*.noarch.rpm' || 'fingerbank*.deb' }}
          ARTIFACTORY_NAME: ${{ inputs._IMAGE_TYPE == 'rhel8' &&  'package-rpm' || 'package-deb' }}